- id: detect-discord-bot-tokens
  name: detect discord bot tokens
  description: Scans the repository for unencrypted Discord bot tokens.
  language: python
  entry: botstrap scan
  args: ["--quiet"]
  pass_filenames: false
  require_serial: true
  always_run: true
  minimum_pre_commit_version: 2.0.0
