- id: detect-discord-bot-tokens
  name: detect discord bot tokens
  description: Prevents unencrypted/plaintext Discord bot tokens from being committed.
  language: pygrep
  entry: '(?a)[\w-]{24,}\.[\w-]{6}\.[\w-]{27,}'

- id: detect-encrypted-tokens
  name: detect encrypted tokens
  description: Prevents files containing Botstrap-encrypted tokens from being committed.
  language: fail
  entry: "*.key files contain encrypted token data and should be gitignored."
  files: '.*\.(?:content|fernet)\.key$'
