name: 🐛 Bug Report
description: Report broken or incorrect behavior.

body:
  - type: markdown
    attributes:
      value:
        # prettier-ignore
        <h3>Before we begin...</h3>
        Hello there! This form is for <b>bug reports</b> only.
        If you're not sure whether what you're experiencing is actually a bug,
        <br>please open a
        <a href="https://github.com/nuztalgia/botstrap/discussions">discussion</a>
        about it instead. Thanks in advance! 💜

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label:
            I'm reasonably sure that what I'm seeing is a bug in this project's code.
          required: true
        - label:
            I've looked through the existing
            [issues](https://github.com/nuztalgia/botstrap/issues) to ensure this isn't
            a duplicate.
          required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description:
        What did you do that caused this bug or error to occur? Numbered steps, details,
        and code snippets (if applicable) are all very helpful!
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run "..."
    validations:
      required: true

  - type: input
    attributes:
      label: Expected Behavior
      description: What did you expect to happen when you performed those steps?
    validations:
      required: true

  - type: input
    attributes:
      label: Actual Behavior
      description: What actually happened? Does it happen consistently?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, please include screenshots to help explain this bug.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description:
        Do you have any more information that could help other people understand this
        bug? If so, please include it here. If not, that's okay!
    validations:
      required: false

  - type: markdown
    attributes:
      value: <h3 align="center">Thanks for taking the time to report a bug! 🐛</h3>
