name: ✨ Feature Request
description: Propose a new feature for this project.

body:
  - type: markdown
    attributes:
      value:
        # prettier-ignore
        <h3>Before we begin...</h3>
        Hello there! This form is for well-defined <b>feature requests</b> only.
        If you're still in the brainstorming phase and/or would just like to
        suggest a general idea, please open a
        <a href="https://github.com/nuztalgia/botstrap/discussions">discussion</a>
        about it instead. Thanks in advance! 💜

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label:
            I've thoroughly conceptualized this feature and can fill in all of the
            required boxes below.
          required: true
        - label:
            I've looked through the existing
            [issues](https://github.com/nuztalgia/botstrap/issues) to ensure this isn't
            a duplicate.
          required: true

  - type: input
    attributes:
      label: Summary
      description:
        Please provide a clear and concise description of your feature request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem
      description:
        What problem(s) does this feature solve? What does it simplify/enable?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Solution
      description:
        Are there any existing solutions to this problem? If so, what are they?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Ideal Solution
      description:
        What is your ideal solution to this problem? What exactly would you like it to
        do? How should it look and/or behave? Details are very helpful!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description:
        Have you considered any alternative implementations or solutions to the problem?
        Please describe how they differ and what they could look like.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Images
      description:
        If applicable, please include images (e.g. screenshots, mockups, gifs) to help
        illustrate what you'd like to see in this feature.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description:
        Do you have any more information that could help other people understand this
        feature request? If so, please include it here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: <h3 align="center">Thanks for taking the time to suggest a feature! ✨</h3>
