name: Tests

on:
  push:
    paths:
      - "botstrap/**.py"
      - "tests/**.py"
  pull_request:
    paths:
      - "botstrap/**.py"
      - "tests/**.py"
  workflow_dispatch:

jobs:
  tox:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11-dev"]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -U pip tox

      - name: Run pytest via tox
        run: tox -e py
