name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      tests:
        description: Run "pytest" & upload coverage
        type: boolean
        required: true
      docs:
        description: Run "mkdocs build"
        type: boolean
        required: true

jobs:
  filter:
    uses: ./.github/workflows/filter.yml
    with:
      filters: |
        botstrap: ["botstrap/**"]
        tests: ["tests/**"]
        docs: ["docs/**"]

  pytest:
    needs: filter
    if: |
      contains(needs.filter.outputs.matches, 'botstrap') ||
      contains(needs.filter.outputs.matches, 'tests')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: 3.11-dev
            os: ubuntu-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python -m pip install -U pip tox

      - name: Run tests and generate coverage report
        run: tox -e py -- --cov-report=xml

      - if: matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest'
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

  mkdocs-build:
    needs: filter
    if: contains(needs.filter.outputs.matches, 'docs')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: docs/requirements.txt

      - name: Install dependencies
        run: python -m pip install -U pip tox

      - name: Run "mkdocs build" via tox
        run: tox -e docs
